name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  share_plus: ^7.2.1
  animate_do: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/Franklin-D-Roosevelt-1937.webp
    - assets/images/images.jpg
    - assets/images/images (1).jpg
    - assets/images/imafges (2).jpg
    - assets/images/licensed-image.jpg
    - assets/images/licensed-image (1).jpg